music_directory "/home/trev/Music"
playlist_directory "~/.local/share/mpd/playlists"
db_file "~/.cache/mpd/database"
state_file "~/.cache/mpd/state"
sticker_file "~/.cache/mpd/sticker.sql"
log_file "~/.cache/mpd/log"

bind_to_address "127.0.0.1"
port "6600"
auto_update "yes"
restore_paused "yes"

audio_output {
  type "pipewire"
  name "PipeWire"
}
