;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(specifications->manifest
  (list "papirus-icon-theme"
        "xdg-desktop-portal-gtk"
        "xdg-dbus-proxy"
        "xdg-desktop-portal"
        "pipewire"
        "xdg-desktop-portal-wlr"
        "git"
        "fuzzel"
        "neofetch"
        "telegram-desktop"
        "git:send-email"
        "weechat"
        "msmtp"
        "pinentry-tty"
        "flatpak-xdg-utils"
        "wireplumber"
        "emacs-pgtk"
        "font-terminus"
        "ncurses"
        "ripgrep"
        "fd"
        "gammastep"
        "pavucontrol"
        "dbus"
        "flatpak"
        "libtool"
        "jq"
        "grimshot"
        "mpv"
        "fzf"
        "zsh"
        "gnupg"
        "kitty"
        "curl"
        "stow"
        "font-google-noto-emoji"
        "direnv"
        "fzf-tab"
        "libvterm"
        "zsh-autopair"
        "zsh-syntax-highlighting"
        "zsh-autosuggestions"
        "zsh-completions"))
