#!/usr/bin/env bash

FEDORA_VERSION=$(rpm -E %fedora)

# COPRs
echo "Adding COPRs..."
sudo wget -4 -O /etc/yum.repos.d/_copr:pgdev:ghostty.repo "https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-$FEDORA_VERSION/pgdev-ghostty-fedora-$FEDORA_VERSION.repo"

echo "Enabling automatic updates..."
sudo sed -i 's/#AutomaticUpdatePolicy.*/AutomaticUpdatePolicy=stage/' /etc/rpm-ostreed.conf
sudo systemctl enable rpm-ostreed-automatic.timer
rpm-ostree cleanup -m

### Setup tools
echo "Installing tools..."
rpm-ostree override remove firefox firefox-langpacks
rpm-ostree install direnv eza fd-find fzf gnome-tweaks ghostty-git kitty mg ripgrep \
  stow zsh zsh-autosuggestions zsh-syntax-highlighting wireguard-tools
