#!/bin/sh

FEDORA_VERSION=$(rpm -E %fedora)
REGISTRY=registry.fedoraproject.org/fedora-toolbox
TOOLBOX_NAME=custom-toolbox-$FEDORA_VERSION

podman container rm fedora-toolbox-"$FEDORA_VERSION" --force
podman image rm $REGISTRY:$FEDORA_VERSION
podman image pull $REGISTRY:$FEDORA_VERSION
podman build --tag $TOOLBOX_NAME -f ~/Workspace/dotfiles/silverblue/containers/Containerfile_fedora --build-arg FEDORA_VERSION="$FEDORA_VERSION" --build-arg USER_HOME="$HOME"
toolbox create -i $TOOLBOX_NAME fedora-toolbox-"$FEDORA_VERSION"
