[buildPlans.Iotrevka]
family = "Iotrevka"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.Iotrevka.variants.design]
four = "closed-serifless"
zero = "dotted"
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "short-serifed"
capital-j = "serifless"
capital-q = "crossing"
capital-w = "rounded-vertical-sides-serifless"
capital-z = "straight-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-earless-corner"
i = "serifed-semi-tailed"
j = "serifless"
l = "semi-tailed"
m = "earless-rounded-double-arch-short-leg-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook"
u = "toothless-rounded-serifless"
v = "straight-serifless"
w = "straight-serifless"
y = "cursive-flat-hook-serifless"
z = "straight-serifless"
capital-eszet = "rounded-serifless"
lower-iota = "tailless"
lower-kappa = "symmetric-connected-serifless"
cyrl-zhe = "symmetric-connected"
cyrl-ze = "serifless"
cyrl-er = "earless-rounded-serifless"
cyrl-u = "cursive-serifless"
cyrl-yeri = "corner"
cyrl-yery = "corner"
tittle = "round"
braille-dot = "square"
asterisk = "hex-high"
ascii-grave = "straight"
ascii-single-quote = "straight"
guillemet = "straight"
at = "fourfold"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.Iotrevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Iotrevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Iotrevka.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Iotrevka.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.Iotrevka.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.Iotrevka.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.Iotrevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Iotrevka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Iotrevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Iotrevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
