(use-modules (gubar gublock)
             (gubar blocks date-time)
             (gubar blocks battery)
             (gubar blocks label)
             (gubar blocks volume-pipewire)
             (gubar blocks network-manager-wifi)
             (gubar blocks xkb-layout)
             (gubar swaybar-protocol))

(list (date-time #:interval 60 #:format "%a %b %d %Y %-I:%M %p")
      (network-manager-wifi)
      (volume-pipewire)
      (xkb-layout #:alias-pairs '((0 . "en") (1 . "ru")))
      (battery #:nerd-icons #t)
      (label "trev"))
