#!/usr/bin/env bash
BRIGHT=$(brightnessctl -m --class=backlight | cut -d, -f4 | tr -d '%')

gdbus call --session \
    --dest org.freedesktop.Notifications \
    --object-path /org/freedesktop/Notifications \
    --method org.freedesktop.Notifications.Notify \
    "swaync" \
    "uint32 0" \
    "display-brightness-symbolic" \
    "" \
    "${BRIGHT}%" \
    '[]' \
    "{\"value\": <int32 $BRIGHT>}" \
    "int32 1500" &>/dev/null
