general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    # after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action="on"})'
}

listener {
    timeout = 150                                # 2.5min.
    on-timeout = sh -c 'hyprctl -j monitors | jq -e ".[] | select(.name == \"eDP-1\")" >/dev/null && brightnessctl -s set 10'
    on-resume = sh -c 'hyprctl -j monitors | jq -e ".[] | select(.name == \"eDP-1\")" >/dev/null && brightnessctl -r'
}

# turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
# listener {
#     timeout = 150                                          # 2.5min.
#     on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 # turn off keyboard backlight.
#     on-resume = brightnessctl -rd rgb:kbd_backlight        # turn on keyboard backlight.
# }

listener {
    timeout = 600
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

listener {
    timeout = 601
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action="off"})'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action="on"})'
}

# Put monitor to sleep after 30 seconds when locked
listener {
   timeout = 30
   on-timeout = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({action="off"})'
   on-resume = hyprctl dispatch 'hl.dsp.dpms({action="on"})'
}

# listener {
#     timeout = 3600
#     on-timeout = loginctl suspend                # suspend pc
# }
