$font = Noto Sans
$color_text = rgba(f4f4f5f2)
$color_text_muted = rgba(f4f4f594)
$color_warning = rgba(f59e0bff)
$color_error = rgba(ef4444ff)

general {
    hide_cursor = true
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    color = rgba(111827ff)
    blur_size = 8
    blur_passes = 5
}

input-field {
    monitor =
    size = 360, 56
    outline_thickness = 2
    inner_color = rgba(121214a0)
    font_color = $color_text_muted

    outer_color = rgba(ffffff1f)
    check_color = $color_warning
    fail_color = $color_error

    fade_on_empty = false
    rounding = 14

    font_family = $font
    placeholder_text = Enter a password...
    fail_text = $PAMFAIL

    dots_size = 0.24
    dots_spacing = 0.25

    position = 0, -56
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font
    color = $color_text

    position = 0, 164
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %-d"
    font_size = 24
    font_family = $font
    color = $color_text_muted

    position = 0, 82
    halign = center
    valign = center
}

label {
    monitor =
    text = $LAYOUT[en,ru]
    font_size = 16
    font_family = $font
    color = $color_text_muted
    onclick = niri msg action switch-layout next

    position = -24, 24
    halign = right
    valign = bottom
}
