;;
;; Add MELPA package manager
;; https://melpa.org
;;

(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
;; and `package-pinned-packages`. Most users will not need or want to do this.
;;(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)

;;
;; Keybindings
;;

(global-set-key (kbd "C-c /") 'comment-line)
(global-set-key (kbd "C-c n") 'next-buffer)
(global-set-key (kbd "C-c p") 'previous-buffer)
(global-set-key (kbd "C-c f r") 'recentf-open-files)
(global-set-key (kbd "C-c f p") '(lambda () "Show current file path" (interactive) (message (buffer-file-name))))
(global-set-key (kbd "C-c k") '(lambda () "Ripgrep" (interactive) (counsel-rg nil nil "--hidden" nil)))
(global-set-key (kbd "C-c f f") 'counsel-fzf)

;;
;; Options
;;

;; Set font for GUI
(add-to-list 'default-frame-alist
	     '(font . "Jetbrains Mono Nerd Font Mono-14"))

;; Hide menu bar, tool bar and scrollbar
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)

;; Column number mode
(column-number-mode t)

;; Nord theme
(load-theme 'nord t)

;; Auto-pairs
(electric-pair-mode)

; Highlight cursor line
(global-hl-line-mode t)

;; Fix vertical split character (terminal)
(set-display-table-slot standard-display-table 'vertical-border ?│)

;; Show relative line numbers
(global-display-line-numbers-mode)
(setq display-line-numbers-type 'relative)

;; No backups
(setq make-backup-files nil)

;; Column number mode
(column-number-mode t)

;; Nord theme
(load-theme 'nord t)

;; Recent files
(recentf-mode 1)

;; Save minibuffer history
(savehist-mode 1)

;; Save place in files
(save-place-mode 1)

;;;
;;; Plugins/Modes
;;;

;; Completion
(add-hook 'after-init-hook 'global-company-mode)

;; Fuzzy finding in minibuffer
(ivy-mode)
(setq enable-recursive-minibuffers t)
(counsel-mode)

;; diff-hl for git markers in margin
(global-diff-hl-mode)
(unless (window-system) diff-hl-margin-mode)
(diff-hl-flydiff-mode)
(setq diff-hl-flydiff-delay 0.3)
(setq diff-hl-margin-symbols-alist '((insert . " ") (delete . " ") (change . " ")
				     (unknown . " ") (words . " ")))

;; Rust
;; (add-hook 'rust-mode-hook 'eglot-ensure)
;; TODO: Maybe use eglot-x for more features

;; Autogenerated stuff
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages '(counsel ivy company diff-hl nord-theme)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
