;;
;; Add MELPA package manager
;; https://melpa.org
;;

(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
;; and `package-pinned-packages`. Most users will not need or want to do this.
;;(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)

;;
;; Keybindings
;;

(global-set-key (kbd "C-c /") 'comment-line)
(global-set-key (kbd "C-c n") 'next-buffer)
(global-set-key (kbd "C-c p") 'previous-buffer)

;;
;; Options
;;

;; Hide menu bar, tool bar and scrollbar
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)

;; Fix vertical split character (terminal)
(set-display-table-slot standard-display-table 'vertical-border ?│)

;; Show relative line numbers
(global-display-line-numbers-mode 1)
(setq display-line-numbers 'relative)

;; No backups
(setq make-backup-files nil)

;; Column number mode
(column-number-mode t)

;; Nord theme
(load-theme 'nord t)

;;;
;;; Plugins
;;;

;; diff-hl for git markers in margin
(global-diff-hl-mode)
(diff-hl-margin-mode)

;; Autogenerated stuff
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages '(diff-hl nord-theme)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
