# vim:ft=kitty

## name: Modus Vivendi Deuteranopia
## author: Protesilaos Stavrou
## license: GPLv3
## blurb: Highly accessible themes made for GNU Emacs, conforming with the highest
## standard for colour contrast between background and foreground values (WCAG AAA)

# The basic colors
foreground              #ffffff
background              #000000
selection_foreground    #ffffff
selection_background    #5a5a5a

# Cursor colors
cursor                  #efef00
cursor_text_color       #000000

# kitty window border colors
active_border_color     #c6daff
inactive_border_color   #646464

# Tab bar colors
active_tab_foreground   #ffffff
active_tab_background   #535353
inactive_tab_foreground #989898
inactive_tab_background #303030

# The basic 16 colors
# black
color0 #000000
color8 #535353

# red
color1 #ff5f59
color9 #ff5f5f

# green
color2  #44bc44
color10 #44df44

# yellow
color3  #cabf00
color11 #efef00

# blue
color4  #2fafff
color12 #338fff

# magenta
color5  #feacd0
color13 #ff66ff

# cyan
color6  #00d3d0
color14 #00eff0

# white
color7  #989898
color15 #ffffff
