#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
# pgrep -x picom > /dev/null || picom &
pgrep -x feh > /dev/null || feh --bg-fill --randomize ~/Pictures/Wallpapers &
pgrep -x redshift > /dev/null || redshift &
pgrep -x telegram-desktop > /dev/null || telegram-desktop &
pgrep -x polybar > /dev/null || polybar mybar &
pgrep -x discord > /dev/null || discord &
pgrep -x alacritty > /dev/null || alacritty &

xsetroot -cursor_name left_ptr &

bspc monitor -d web work code chat

bspc config border_width         8
# Nord
# bspc config normal_border_color  "#434C5E"
# bspc config focused_border_color "#EBCB8B"
# Challenger deep
bspc config normal_border_color  "#292C3E"
bspc config focused_border_color "#a36900"
bspc config window_gap           30

bspc config focus_follows_pointer true 

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a *:google-chrome desktop='^2' follow=on
bspc rule -a TelegramDesktop:* desktop='^4'
bspc rule -a *:discord desktop='^4' 
bspc rule -a Alacritty desktop='^4' follow=off --one-shot
bspc rule -a Emacs state=tiled
