#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
# pgrep -x picom > /dev/null || picom &
pgrep -x polybar > /dev/null || polybar mybar &
pgrep -x feh > /dev/null || feh --bg-fill --randomize ~/Pictures/Wallpapers &
pgrep -x redshift > /dev/null || redshift &
pgrep -x telegram-desktop > /dev/null || telegram-desktop &
pgrep -x discord > /dev/null || discord &

xsetroot -cursor_name left_ptr &

bspc monitor -d web work code chat

bspc config border_width         4
bspc config normal_border_color  "#595959"
bspc config focused_border_color "#B27300"
bspc config window_gap           30

bspc config focus_follows_pointer true 

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a *:google-chrome desktop='^2' follow=on
bspc rule -a TelegramDesktop:* desktop='^4' --one-shot
bspc rule -a *:discord desktop='^4' follow=off
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
